version: '3.4'
services:
  mongodb:
    image: mongo:6.0.5
    ports:
      - "27017:27017"
    container_name: mongodb_bot_local
    network_mode: bridge

  rabbit:
    container_name: amqp_bot
    image: rabbitmq:3.13.1-management-alpine
    environment:
      - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
      - RABBITMQ_DEFAULT_USER=adm
      - RABBITMQ_DEFAULT_PASS=123456
      - RABBITMQ_DEFAULT_VHOST=virtualhost
    ports:
      - 15672:15672
      - 5672:5672
    network_mode: bridge