require('dotenv').config()
console.log('dotenv loaded')
require('./src/config-ffmpeg')
console.log('config-ffmpeg loaded')
require('./src/bot')
console.log('bot loaded')
require('./src/telegram')
console.log('telegram loaded')
require('./src/global-exception-handler')
console.log('global-exception-handler loaded')