module.exports = {
  BOT_TOKEN: process.env.BOT_TOKEN,

  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,

  ASSISTANT_ID: process.env.ASSISTANT_ID,
  ASSISTANT_IAM_APIKEY: process.env.ASSISTANT_IAM_APIKEY,
  KEY_OPEN_AI: process.env.KEY_OPEN_AI,

  SENTRY_DNS: process.env.SENTRY_DNS,

  GITHUB_API_TOKEN: process.env.GITHUB_API_TOKEN,

  CAIXINHA_KEY: process.env.CAIXINHA_KEY,
  CAIXINHA_SERVER_URL: process.env.CAIXINHA_SERVER_URL,

  COMMUNICATION_SERVER_URL: 'https://communication-service-4f4f57e0a956.herokuapp.com',

  AMQP_CONNECTION: process.env.AMQP_CONNECTION,
  
  FINANCE_API_AUTH: process.env.FINANCE_API_AUTH,

  TELEGRAM_API_KEY: process.env.TELEGRAM_API_KEY,

  MONGO_URL: process.env.MONGO_URL,
  
  ADMIN_KC_USERNAME: process.env.ADMIN_KEYCLOACK_USERNAME,
  ADMIN_KC_PASSWORD: process.env.ADMIN_KEYCLOACK_PASSWORD,
  ADMIN_KC_CLIENT_ID: process.env.ADMIN_KEYCLOACK_CLIENT_ID,

  CLOUD_CONVERT_API: process.env.CLOUD_CONVERT_API,

  DISABLE_AUTO_ARBITRAGE: process.env.DISABLE_AUTO_ARBITRAGE,
}
