module.exports = {
  BOT_TOKEN: process.env.BOT_TOKEN,
  B3_API_KEY: process.env.B3_API_KEY,
  MAILGUN_API_KEY: process.env.MAILGUN_API_KEY,
  BASIC_MAILGUN_KEY: process.env.BASIC_MAILGUN_KEY,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
}
