module.exports = {
  BOT_TOKEN: process.env.BOT_TOKEN,
  MAILGUN_API_KEY: process.env.MAILGUN_API_KEY,
  BASIC_MAILGUN_KEY: process.env.BASIC_MAILGUN_KEY,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  ASSISTANT_ID: process.env.ASSISTANT_ID,
  ASSISTANT_IAM_APIKEY: process.env.ASSISTANT_IAM_APIKEY,
  SENTRY_DNS: process.env.SENTRY_DNS,
  GITHUB_API_TOKEN: process.env.GITHUB_API_TOKEN,
  CAIXINHA_KEY: process.env.CAIXINHA_KEY,
  AMQP_CONNECTION: process.env.AMQP_CONNECTION,
  CAIXINHA_SERVER_URL: process.env.CAIXINHA_SERVER_URL
}
