# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test --if-present
    
  heroku:
    needs: [build]
    runs-on: ruby-latest
    
    steps:
      - name: Apt Get Update
        run: apt-get update -qy
      - name: Install ruby dev
        run: apt-get install -y ruby-dev
      - name: Install dpl
        run: gem install dpl
      - name: Deploy heroku
        run: dpl --provider=heroku --app=binno-worker --api-key=${{ secrets.FABIOHP_HEROKU_KEY }}
  
